<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PcPrizePick.Domain\PcPrizePick.Domain.csproj" />
    <ProjectReference Include="..\PcPrizePick.SharedKernel\PcPrizePick.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PcPrizePick.Tests" />
  </ItemGroup>

</Project>
